#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Thu May 31 14:23:21 2018

@author: enumera-air
"""

#Visualising the geographical data

housing.plot(kind="scatter", x="longitude", y="latitude", alpha=0.1, s= housing['population']/100, label='population', figsize=(10,7), c='median_house_value', cmap=plt.get_cmap("jet"), colorbar=True)

plt.legend()


#setting the alpha to 0.1 allow places of higher density to show up
