#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Thu May 31 18:25:31 2018

@author: enumera-air
"""

#Combining categorical and numerical transformed features.

housing_prepared = housing

housing_prepared.head()

#Need to find a way of piping the test data through the same code

