#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Thu May 31 21:02:05 2018

@author: enumera-air
"""

#Measurement



def display_scores(scores):
    print("Scores:", scores)
    print("Mean:", scores.mean())
    print("Standard Deviation:", scores.std())
    
def cross_validate(model,X,y):
    scores = cross_val_score(model, X, y, scoring='neg_mean_squared_error', cv=10)
    rmse_scores = np.sqrt(-scores)
    display_scores(rmse_scores)
    
    
def basic_prediction(model, X, y):
    housing_predictions = model.predict(X)
    mse = mean_squared_error(y, X)
    rmse = np.sqrt(mse)
    print("RMSE:",rmse)

