#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Thu May 31 21:37:22 2018

@author: enumera-air
"""

#Fine Tuning

param_grid = [{'n_estimators': [3,10,30], 'max_features':[2,4,6,8]}, {'bootstrap': [False], 'n_estimators':[3,10], 'max_features':[2,3,4]},]

forest_regGS = RandomForestRegressor()

grid_search = GridSearchCV(forest_regGS, param_grid,cv=5,scoring='neg_mean_squared_error')

grid_search.fit(housing_prepared, housing_labels)

grid_search.best_params_

cvres = grid_search.cv_results_

for mean_score, params in zip(cvres['mean_test_score'], cvres["params"]):
    print(np.sqrt(-mean_score), params)