#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Thu May 31 13:59:08 2018

@author: enumera-air
"""

#Creating Stata

housing["income_cat"] = np.ceil(housing["median_income"]/1.5)
housing["income_cat"].where(housing["income_cat"]<5, 5.0, inplace=True)

housing["income_cat"].hist(bins=50, figsize=(20,15))

#Creating a stratified datasets

split = StratifiedShuffleSplit(n_splits=1, test_size=0.2, random_state=42)

for train_index, test_index in split.split(housing, housing['income_cat']):
    strat_train_set = housing.loc[train_index]
    strat_test_set = housing.loc[test_index]
    
housing["income_cat"].value_counts() / len(housing)

strat_train_set['income_cat'].value_counts() / len(housing)
strat_test_set['income_cat'].value_counts() / len(housing)

for set_ in (strat_train_set, strat_test_set):
    set_.drop("income_cat", axis=1, inplace=True)
  
    
#Within the training set we have created a training and test set that is
#properly stratified with the median income ranges.

housing = strat_train_set.copy()
    

