#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Thu May 31 14:28:53 2018

@author: enumera-air
"""

#Looking for correlations

corr_matrix = housing.corr()

corr_matrix ["median_house_value"].sort_values(ascending=False)


attributes = ["median_house_value", "median_income", "total_rooms", "housing_median_age"]

scatter_matrix(housing[attributes], figsize=(12,8))

housing.plot(kind="scatter", x="median_income",y="median_house_value",alpha=0.1)
