#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Thu May 31 14:35:04 2018

@author: enumera-air
"""

#Creating new features

def AddNewFeatures(df):
    df["rooms_per_household"] = df["total_rooms"]/df["households"]
    df["bedrooms_per_room"] = df["total_bedrooms"]/df["total_rooms"]
    df["population_per_household"] = df["population"]/df["households"]
    return df

AddNewFeatures(housing)