#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Sun Jun  3 01:02:13 2018

@author: enumera-air
"""

#Classification

from sklearn.datasets import fetch_mldata

mnist = fetch_mldata('MNIST original')
mnist


X,y =mnist['data'], mnist['target']
X.shape
y.shape

some_digit = X[36000]
some_digit_image = some_digit.reshape(28,28)

plt.imshow(some_digit_image, cmap=mcm.binary, interpolation='nearest')
plt.axis('off')
plt.show()




