#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Sun Jun  3 01:24:51 2018

@author: enumera-air
"""

#Stochastic Gradient Descent

sgd_clf = SGDClassifier(random_state=42)

sgd_clf.fit(X_train, y_train_5)


sgd_clf.predict([some_digit])
